# Generated by Django 3.2.7 on 2021-12-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20211212_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, default='00000', max_length=122)),
                ('surname', models.CharField(blank=True, default='00000', max_length=122)),
                ('birthdate', models.CharField(blank=True, default='00000', max_length=122)),
                ('adharcard', models.CharField(blank=True, default='00000', max_length=122)),
                ('passport', models.CharField(blank=True, default='00000', max_length=122)),
                ('martial', models.CharField(blank=True, default='00000', max_length=122)),
                ('email', models.CharField(blank=True, default='00000', max_length=122)),
                ('address', models.CharField(blank=True, default='00000', max_length=122)),
                ('residential', models.CharField(blank=True, default='00000', max_length=122)),
                ('phonenumber', models.CharField(blank=True, default='00000', max_length=122)),
                ('occupation', models.CharField(blank=True, default='00000', max_length=122)),
                ('commencement', models.CharField(blank=True, default='00000', max_length=122)),
                ('income', models.CharField(blank=True, default='00000', max_length=122)),
                ('registered', models.CharField(blank=True, default='00000', max_length=122)),
            ],
        ),
    ]
